// <auto-generated />
using BuyerAPI.Infrastructure.Data.DbConnectionContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BuyerAPI.Migrations
{
    [DbContext(typeof(BuyerDbContext))]
    [Migration("20241111140408_buyertables")]
    partial class buyertables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuyerAPI.Entities.Bill", b =>
                {
                    b.Property<int>("BillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BillID"));

                    b.Property<string>("BuyerTaxID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InovoiceStatus")
                        .HasColumnType("integer");

                    b.Property<decimal>("InvoiceCost")
                        .HasColumnType("numeric");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuplierTaxID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TermDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BillID");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("BuyerAPI.Entities.Buyer", b =>
                {
                    b.Property<string>("BuyerID")
                        .HasColumnType("text");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BuyerID");

                    b.ToTable("Buyers");
                });
#pragma warning restore 612, 618
        }
    }
}
